---
title: "NMF"
output: html_notebook
---

Here we have a very clear example of the benetifs of using Boolean NMF [Boolean NMF](https://people.mpi-inf.mpg.de/~pmiettin/slides/BooleanMatrixFactorization_UMannheim2014.pdf) 


The R package *NMF* that Ive used so far is documented here: 
The paper: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-367
The vignette: https://cran.r-project.org/web/packages/NMF/index.html
##List of algorithms on the package
# nmfAlgorithm()
# ##  [1] "brunet"    "KL"        "lee"
# ##  [6] "nsNMF"     "ls-nmf"    "pe-nmf"
# ## [11] "snmf/l"
# meth <- nmfAlgorithm(version = "R")
# meth <- c(names(meth), meth)
# meth




Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Cmd+Shift+Enter*. 

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

