---
title: "Results of ovarian data"
output: html_notebook
---

*NBS*

This is obtained by:
1. network propagation and quantile normalization
2. NMF factorization (net nmf) k=4
3. assign cluster indexes to the index with maximum score

References and clarifications
3)
Let's say Y is the matrix with Patients as rows and k columns after NMF. Then, a patient is assigned to the index of the column with the maximum value.

This was implemented using the nmf tool box https://sites.google.com/site/nmftool/
Y. Li and A. Ngom, "The non-negative matrix factorization toolbox for biological data mining," BMC Source Code for Biology and Medicine, vol 8, pp. 10, April 2013.

The script name is NMFCluster.m


pvalue =  0.00406846

*Standard NMF*

This is obtained without any network smoothing, just NNLS based NMF (non-negative-constrained least squares)
k=4
clustering index assigned to the maximum score

pvalue = 0.2653275 

*NBS with concensus clustering*

This is obtained by:
1. network propagation and quantile normalization
2. NMF factorization (net nmf) k=4
3. CC with 100 reperitions, 80% of the samples, nmf clustering, k = [2,3,4]
4. assign to clusters using average linkage herarchical clustering of the patients' similarity matrix obtained with CC

pvalue = 0.007446442  

References and clarifications
4)
From consensus clustering, we obtain a patient similarity matrix. To assign labels to patients, they use average linkage hierarchical clustering.

The script name is calc_label.m

This is the method they use to compute average linkage https://www.mathworks.com/help/stats/linkage.html

*Standard CC*

Main script: nbs_cc_main.m
This is obtained without any network smoothing, just concensus clustering with the following steps:

1. Run NMF with k = [2,3,4], 80% of samples, and 100 repetitions. Assign label using max score, like explained above. 
2. From the 300 partitionings, build the patient similarity matrix (consensus clustering)
script: "hmat_to_cc_cluster.m"
3. Assign labels to patients (usign average linkage herarchical clustering)


p-value = 0.2551205 


*Rubik smooth*

1. change data format using 1-2v3-BoolMatrices_Ovarian.R
2. Copy files to Rubik folder /Users/diamac/10-Research/4Current/CLINGEN/9source/rubik/data 
3. Import csv files as Numeric Matrix and save the scripts. Change variable name at the bottom.
4. run_cligen.m
tensor is the smoothed value on the mutation matrix for each true value in the clinical matrix






```{r}
source('~/CLIGEN_tgit/R/9-OV/SAfromMatlabResultsOV.R', echo=TRUE)
```
After runing the above I got these results: 
 
results: 
 
NBS pvalue 	 0.00406846 
NMF pvalue 	 0.2653275 
NBS_cc pvalue 	 0.007446442 
CC pvalue 	 0.2551205
